# replace default config
# full: true

plugins:

  # - name
  #
  # or:
  # - name: false
  # - name: true
  #
  # or:
  # - name:
  #     param1: 1
  #     param2: 2
  - cleanupAttrs: true
  - cleanupEnableBackground: true
  - cleanupIDs: true
  - cleanupNumericValues:
      floatPrecision: 1
  - collapseGroups: true
  - convertColors: true
  - convertPathData:
      floatPrecision: 1
  - convertShapeToPath: true
  - convertStyleToAttrs: true
  - convertTransform:
      floatPrecision: 1
  - mergePaths: true
  - moveElemsAttrsToGroup: true
  - moveGroupAttrsToElems: true
  - removeAttrs:
      attrs:
        - fill
        - width
        - height
        - fill-rule
  - removeComments: true
  - removeDoctype: true
  - removeEditorsNSData: true
  - removeEmptyAttrs: true
  - removeEmptyContainers: true
  - removeEmptyText: true
  - removeHiddenElems: true
  - removeMetadata: true
  - removeNonInheritableGroupAttrs: true
  - removeRasterImages: true
  - removeTitle: true
  - removeUnknownsAndDefaults: true
  - removeUnusedNS: true
  - removeUselessStrokeAndFill: true
  - removeViewBox: false
  - removeXMLProcInst: true
  - sortAttrs: true
  - transformsWithOnePath:
      floatPrecision: 1
